### ISSUE TITLE
stream.on is not a function

### ISSUE THREAD

**Issue by whydna** [moshisushi/hlsjs-ipfs-loader#1] opened 2018-01-14 02:01 UTC
I'm getting the following error after following the instructions in the README.

Any idea whats wrong?

```
dist/index.js:167 Uncaught TypeError: stream.on is not a function
    at index.js:167
    at pull.collect (files.js:227)
    at reduce.js:10
    at drain.js:20
    at map.js:19
    at next (index.js:22)
    at index.js:39
    at Array.<anonymous> (index.js:10)
    at next (index.js:26)
    at index.js:39
```

**Comment by lucaslg26** [comment] 2018-01-14 05:14
+1

**Comment by lucaslg26** [comment] 2018-01-14 05:33
The problem is in [ipfs.files.cat function](https://github.com/moshisushi/hlsjs-ipfs-loader/blob/master/src/index.js#L93), hlsjs-ipfs-loader expects an stream data to pipe and receives a Uint8Array that isn't directly readable.
I'll check better tomorrow.

**Comment by moshisushi** [comment] 2018-01-14 11:47
Thanks for making me aware of this. Must be a change to how ipfs.files.cat works... I’ll will look into this as soon as possible (or if you already have a patch for this feel free to create a pull request). Cheers

**Comment by lucaslg26** [comment] 2018-01-14 13:51
I fixed the problem, I'll a pull request in some minutes.

**Comment by moshisushi** [comment] 2018-01-14 16:06
Thanks a lot! I’ll publish a new npm version when I’m at the computer.

**Comment by moshisushi** [comment] 2018-01-14 21:37
Alright, version 0.1.2 has been published and the example now runs fine (tested in Firefox as well).

https://www.npmjs.com/package/hlsjs-ipfs-loader

Closing this issue now. Thanks again @lucaslg26 for the patch!

**Closed by moshisushi** 2018-01-14 21:37 UTC

**Comment by whydna** [comment] 2018-01-14 21:47
Wow thank you guys!
